"""Generate `ingestion/countries.py`: what a results file may write in its nationality column, as
ISO 3166-1 alpha-3.

    python scripts/generate_country_table.py

Reads the `i18n-iso-countries` package the website already uses (`npm install` first), so the
upload and the country field agree. Results files write nationality as "FRA", "FR", "France",
"Frankreich", "GER" (the Olympic code) or "ประเทศไทย"; all of them should read as one code.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from ingestion.schema import _normalize_header  # noqa: E402

PACKAGE = ROOT / "node_modules" / "i18n-iso-countries"
LANGUAGES = ["en", "fr", "de", "es", "it", "pt", "nl", "th"]

# Olympic (IOC) and other sporting codes that differ from ISO alpha-3, as timing software writes them.
SPORT_CODES = {
    "GER": "DEU", "SUI": "CHE", "NED": "NLD", "POR": "PRT", "DEN": "DNK", "GRE": "GRC", "CRO": "HRV", "SLO": "SVN", "BUL": "BGR", "LAT": "LVA",
    "RSA": "ZAF", "INA": "IDN", "MAS": "MYS", "PHI": "PHL", "SIN": "SGP", "VIE": "VNM", "TPE": "TWN", "MYA": "MMR", "CAM": "KHM", "NEP": "NPL",
    "SRI": "LKA", "IRI": "IRN", "KSA": "SAU", "UAE": "ARE", "KUW": "KWT", "OMA": "OMN", "BRN": "BHR", "LIB": "LBN", "MGL": "MNG", "BAN": "BGD",
    "BHU": "BTN", "CHI": "CHL", "URU": "URY", "PAR": "PRY", "CRC": "CRI", "GUA": "GTM", "HON": "HND", "ESA": "SLV", "NCA": "NIC", "HAI": "HTI",
    "PUR": "PRI", "BAR": "BRB", "BAH": "BHS", "ALG": "DZA", "ANG": "AGO", "BOT": "BWA", "BUR": "BFA", "CHA": "TCD", "CGO": "COG", "GAM": "GMB",
    "GUI": "GIN", "LES": "LSO", "LBA": "LBY", "MAD": "MDG", "MAW": "MWI", "MTN": "MRT", "MRI": "MUS", "NIG": "NER", "NGR": "NGA", "SEY": "SYC",
    "SUD": "SDN", "TAN": "TZA", "TOG": "TGO", "ZAM": "ZMB", "ZIM": "ZWE", "FIJ": "FJI", "SAM": "WSM", "TGA": "TON", "VAN": "VUT", "MON": "MCO",
    "ENG": "GBR", "SCO": "GBR", "WAL": "GBR", "NIR": "GBR", "UK": "GBR",
}
# Everyday names the package does not carry.
EXTRA_NAMES = {
    "usa": "USA", "u s a": "USA", "united states": "USA", "america": "USA", "uk": "GBR", "great britain": "GBR", "england": "GBR", "scotland": "GBR", "wales": "GBR",
    "northern ireland": "GBR", "holland": "NLD", "south korea": "KOR", "korea": "KOR", "north korea": "PRK", "russia": "RUS", "czech republic": "CZE", "vietnam": "VNM",
    "laos": "LAO", "hong kong": "HKG", "macau": "MAC", "taiwan": "TWN", "chinese taipei": "TWN", "iran": "IRN", "syria": "SYR", "bolivia": "BOL", "venezuela": "VEN",
    "tanzania": "TZA", "moldova": "MDA", "turkey": "TUR", "ivory coast": "CIV", "reunion": "REU", "la reunion": "REU", "deutschland": "DEU", "schweiz": "CHE",
    "suisse": "CHE", "svizzera": "CHE", "osterreich": "AUT", "espana": "ESP", "italia": "ITA", "ไทย": "THA", "ประเทศไทย": "THA",
}


def key(text: str) -> str:
    return _normalize_header(text)  # the same key the upload looks a nationality up with


def main() -> None:
    codes = json.loads((PACKAGE / "codes.json").read_text(encoding="utf-8"))
    alpha2 = {a2: a3 for a2, a3, *_ in codes}
    names: dict[str, str] = {}
    for language in LANGUAGES:
        table = json.loads((PACKAGE / "langs" / f"{language}.json").read_text(encoding="utf-8"))["countries"]
        for a2, value in table.items():
            for name in value if isinstance(value, list) else [value]:
                names.setdefault(key(name), alpha2[a2])
    for name, code in EXTRA_NAMES.items():
        names[key(name)] = code
    names = {name: code for name, code in names.items() if name and len(name) >= 3}

    lines = [
        '"""Country codes and names a results file may use, as ISO 3166-1 alpha-3.',
        "",
        "Generated by scripts/generate_country_table.py from the i18n-iso-countries package the website",
        'uses. Do not edit by hand."""',
        "",
        f"ALPHA2 = {json.dumps(dict(sorted(alpha2.items())), ensure_ascii=False)}",
        "",
        f"SPORT_CODES = {json.dumps(dict(sorted(SPORT_CODES.items())), ensure_ascii=False)}",
        "",
        f"NAMES = {json.dumps(dict(sorted(names.items())), ensure_ascii=False)}",
        "",
    ]
    (ROOT / "ingestion" / "countries.py").write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{len(alpha2)} countries, {len(names)} names, {len(SPORT_CODES)} sporting codes")


if __name__ == "__main__":
    main()
