import React from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowUpRight, ChevronDown, Database, GitBranch, Mountain, ShieldCheck } from 'lucide-react'
import './styles.css'

const principles=[['OPEN','Source code and methodology are public.'],['TRANSPARENT','Scores can be inspected and explained.'],['REPRODUCIBLE','Same inputs and version produce the same result.'],['TRACEABLE','Data provenance and permissions are recorded.'],['INDEPENDENT','OTRI develops its own methodology and infrastructure.']]
const pipeline=[['01','RESULTS','Official race data'],['02','VALIDATE','Quality checks'],['03','COURSE','Distance + elevation'],['04','MODEL','Versioned scoring'],['05','INDEX','Reproducible output']]

function Logo(){return <a href="#top" className="logo"><span className="logoMark">O</span><span className="logoText">TRI</span></a>}
function App(){return <div id="top" className="site">
<header className="topbar"><div className="shell nav"><Logo/><div className="devBadge"><i/> IN DEVELOPMENT <span>v0.x</span></div><nav><a href="#why">Why</a><a href="#model">Model</a><a href="#principles">Principles</a><a className="navGithub" href="https://github.com/OTRI-run/otri">GitHub <ArrowUpRight size={14}/></a></nav><a className="mobileGithub" href="https://github.com/OTRI-run/otri">GitHub <ArrowUpRight size={13}/></a></div></header>
<main>
<section className="hero"><div className="shell heroGrid"><div className="heroCopy"><div className="eyebrow">OPEN TRAIL RUNNING INDEX <span>·</span> PERFORMANCE INFRASTRUCTURE</div><h1>Trail performance<br/><em>needs context.</em></h1><p>Finish time alone cannot describe a trail performance. OTRI is building an open performance layer using race results, course data and race context.</p><div className="heroActions"><a className="button primary" href="#model">See how it works <ChevronDown size={15}/></a><a className="button secondary" href="https://github.com/OTRI-run/otri">View source <ArrowUpRight size={15}/></a></div><div className="trustLine"><span>OPEN</span><span>TRANSPARENT</span><span>REPRODUCIBLE</span><span>INDEPENDENT</span></div></div>
<div className="indexPanel"><div className="panelTop"><span>OTRI / INDEX ENGINE</span><span className="live"><i/> BUILDING</span></div><div className="panelScore"><small>THE INPUT</small><strong>CONTEXT</strong><span>turns race data into comparable performance</span></div><div className="panelRows"><div><Database size={16}/><span>RESULTS</span><small>official data</small></div><div><Mountain size={16}/><span>COURSE</span><small>distance · elevation</small></div><div><ShieldCheck size={16}/><span>VALIDATION</span><small>quality + provenance</small></div></div><div className="panelBottom"><b>OTRI INDEX</b><span>VERSIONED · REPRODUCIBLE</span></div></div></div></section>
<section id="why" className="section white"><div className="shell"><div className="sectionIntro"><div className="sectionNo">01</div><div><p className="sectionTag">WHY</p><h2>Same distance.<br/><span>Different challenge.</span></h2></div><p>A 50 km race can be fast and runnable, or steep, technical and mountainous. Distance, elevation, terrain, course design, field strength, weather and altitude change what a finish time means.</p></div><div className="raceCompare"><div><small>RACE A</small><b>50 km</b><span>+1,200 m · RUNNABLE</span></div><div className="notEqual">≠</div><div><small>RACE B</small><b>50 km</b><span>+3,400 m · TECHNICAL</span></div></div></div></section>
<section id="model" className="section soft"><div className="shell"><div className="sectionTop"><p className="sectionTag">02 / MODEL</p><a href="https://github.com/OTRI-run/otri/blob/main/METHODOLOGY.md">Open methodology <ArrowUpRight size={14}/></a></div><div className="modelGrid"><div><h2>Open method.<br/><span>Traceable result.</span></h2><p>OTRI is being built so the scoring process can be understood, tested and reproduced. Official results and documented course data are validated before scoring.</p><div className="equation"><GitBranch size={16}/><span>same inputs + same scoring version</span><b>=</b><span>same result</span></div></div><div className="pipeline">{pipeline.map(([n,title,desc])=><div key={n}><b>{n}</b><strong>{title}</strong><span>{desc}</span><ArrowUpRight size={14}/></div>)}</div></div></div></section>
<section id="principles" className="section navy"><div className="shell"><div className="sectionTop"><p className="sectionTag">03 / PRINCIPLES</p><span className="noBox">NO BLACK BOX</span></div><h2>Built in the open.</h2><div className="principles">{principles.map(([title,desc])=><article key={title}><small>{title}</small><p>{desc}</p></article>)}</div></div></section>
<section className="section organizer"><div className="shell organizerGrid"><div><p className="sectionTag">04 / ORGANIZERS</p><h2>Start with<br/><span>official results.</span></h2></div><div><p>Race organizers provide official results and course details. OTRI validates the inputs and calculates the index.</p><a className="inlineLink" href="https://github.com/OTRI-run/otri/blob/main/docs/organizer-upload.md">Organizer documentation <ArrowUpRight size={14}/></a></div></div></section>
<section className="closing"><div className="shell"><p className="sectionTag">OPEN TRAIL RUNNING INDEX</p><h2>Compare trail performances.<br/><span>Not just finish times.</span></h2><a className="button whiteButton" href="https://github.com/OTRI-run/otri">Explore OTRI <ArrowUpRight size={15}/></a></div></section>
</main><footer><div className="shell"><Logo/><span>OPEN · TRANSPARENT · REPRODUCIBLE · INDEPENDENT</span></div></footer>
</div>}

createRoot(document.getElementById('root')).render(<App />)
