import React from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, ArrowUpRight, GitBranch, Mail } from 'lucide-react'
import Logo from './components/Logo'
import GitHubMark from './components/GitHubMark'
import BuildBanner from './components/BuildBanner'
import ErrorBoundary from './components/ErrorBoundary'
import ExamplePreview from './components/ExamplePreview'
import { initMonitoring } from './lib/monitoring'
import { countPages } from './lib/analytics'
import './styles.css'

initMonitoring()
countPages()

const principles=[['OPEN','Source code and methodology are public.'],['TRANSPARENT','Scores can be inspected and explained.'],['REPRODUCIBLE','Same inputs and version produce the same result.'],['TRACEABLE','Data provenance and permissions are recorded.'],['INDEPENDENT','OTRI develops its own methodology and infrastructure.']]
const pipeline=[['01','RESULTS','Official race data'],['02','VALIDATE','Quality checks'],['03','COURSE','Distance + elevation'],['04','MODEL','Versioned scoring'],['05','INDEX','Reproducible output']]

// The header says the same things as the app's header: where to start, and the example to try.
const NAV=[['How it works','prototype/#home'],['Calculator','prototype/#calculator'],['Races','prototype/#races'],['FAQ','prototype/#faq']]
const EXAMPLE_HREF='prototype/#score?example=1'
const FOCUS='focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600'

function App(){return <div id="top" className="min-h-screen max-w-full overflow-x-clip bg-[#f7f9fc] text-[#0b1220]">
<header className="sticky top-0 z-50 h-[68px] border-b border-slate-200/90 bg-white/95 backdrop-blur"><div className="mx-auto flex h-full min-w-0 w-[min(1120px,calc(100%-28px))] items-center"><Logo/><nav className="ml-auto hidden shrink-0 items-center gap-7 md:flex">{NAV.map(([label,href])=><a key={label} href={href} className={`text-[13px] font-medium text-slate-500 no-underline hover:text-slate-950 ${FOCUS}`}>{label}</a>)}<a className={`inline-flex min-h-9 items-center gap-1 rounded-lg bg-blue-700 px-3 text-[13px] font-semibold text-white no-underline hover:bg-blue-800 ${FOCUS}`} href={EXAMPLE_HREF}>Try an example <ArrowRight size={14} aria-hidden="true"/></a></nav><a className={`ml-auto flex shrink-0 items-center gap-1 rounded-lg bg-blue-700 px-3 py-2 text-xs font-semibold text-white no-underline md:hidden ${FOCUS}`} href={EXAMPLE_HREF}>Try an example <ArrowRight size={13} aria-hidden="true"/></a></div></header>
<div className="border-b border-slate-200 bg-white md:hidden"><nav className="mx-auto flex w-[min(1120px,calc(100%-28px))] items-center gap-5 overflow-x-auto">{NAV.map(([label,href])=><a key={label} href={href} className={`whitespace-nowrap py-3 text-[13px] font-medium text-slate-500 no-underline hover:text-slate-950 ${FOCUS}`}>{label}</a>)}</nav></div>
<a className="skip-link" href="#main">Skip to content</a>
<main id="main">
<section className="relative overflow-hidden border-b border-slate-200 bg-[radial-gradient(circle_at_78%_28%,rgba(37,99,235,.12),transparent_30%),linear-gradient(180deg,#fff_0%,#f8fbff_100%)]"><div className="mx-auto grid min-w-0 w-[min(1120px,calc(100%-28px))] items-center gap-10 py-12 sm:py-16 lg:grid-cols-[minmax(0,1fr)_minmax(0,480px)] lg:gap-14"><div className="min-w-0"><p className="font-mono text-[11px] font-medium tracking-[.1em] text-blue-700">TRAIL SCORES. OPEN TO EVERYONE.</p><h1 className="mt-4 text-[clamp(38px,5.6vw,68px)] font-bold leading-[1.04] tracking-[-.06em]">Know your score.<br/><span className="bg-gradient-to-r from-blue-700 via-blue-500 to-cyan-400 bg-clip-text pb-1 text-transparent">Before you race.</span></h1><p className="mt-6 max-w-[58ch] text-[16px] leading-7 text-slate-700 sm:text-[17px]">Turn your course GPX and race results into explained trail scores. Try scoring without an account, then choose whether to publish a race page your runners can view without signing in or subscribing.</p><div className="mt-7 flex flex-col gap-2 sm:flex-row"><a className={`inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-blue-700 px-4 text-[13px] font-semibold text-white no-underline hover:bg-blue-800 ${FOCUS}`} href={EXAMPLE_HREF}>Try an example race <ArrowRight size={15} aria-hidden="true"/></a><a className={`inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white/90 px-4 text-[13px] font-semibold text-[#0b1220] no-underline hover:border-blue-300 ${FOCUS}`} href="prototype/#calculator">Open the calculator</a></div><p className="mt-5 text-[12px] font-medium text-slate-500">Free scoring · Public results without sign-in · Open methodology</p><a href="prototype/#score" className={`mt-4 inline-flex items-center gap-1 text-[13px] font-semibold text-blue-700 no-underline hover:underline ${FOCUS}`}>Have your own files? Score my race <ArrowRight size={14} aria-hidden="true"/></a></div>
<ExamplePreview base="prototype/" className="min-w-0"/></div></section>
<section id="why" className="bg-white py-14 sm:py-20"><div className="mx-auto w-[min(1120px,calc(100%-28px))]"><div className="grid min-w-0 items-end gap-6 md:grid-cols-[34px_minmax(0,1fr)_minmax(0,.8fr)]"><div className="font-mono text-xs text-blue-600">01</div><div className="min-w-0"><p className="mb-3 font-mono text-[11px] tracking-[.08em] text-slate-500">WHY</p><h2 className="text-[clamp(38px,5vw,62px)] font-bold leading-[.94] tracking-[-.06em]">Same distance.<br/><span className="bg-gradient-to-r from-blue-700 to-cyan-500 bg-clip-text text-transparent">Different challenge.</span></h2></div><p className="min-w-0 text-sm leading-7 text-slate-500">A 50 km race can be fast and runnable, or steep, technical and mountainous. Distance, elevation, terrain, course design, field strength, weather and altitude change what a finish time means.</p></div><div className="mt-10 grid grid-cols-[minmax(0,1fr)_42px_minmax(0,1fr)] border-y border-slate-200"><div className="min-w-0 px-2 py-5 sm:px-5"><small className="font-mono text-[9px] tracking-[.08em] text-blue-600">RACE A</small><b className="mt-2 block text-3xl font-bold tracking-[-.06em]">50 km</b><span className="font-mono text-[8px] tracking-[.05em] text-slate-500">+1,200 m · RUNNABLE</span></div><div className="grid place-items-center text-xl text-blue-600">≠</div><div className="min-w-0 border-l border-slate-200 px-2 py-5 sm:px-5"><small className="font-mono text-[9px] tracking-[.08em] text-blue-600">RACE B</small><b className="mt-2 block text-3xl font-bold tracking-[-.06em]">50 km</b><span className="font-mono text-[8px] tracking-[.05em] text-slate-500">+3,400 m · TECHNICAL</span></div></div></div></section>
<section id="model" className="bg-[linear-gradient(135deg,#f3f7fc_0%,#eef4ff_55%,#f7fbff_100%)] py-14 sm:py-20"><div className="mx-auto w-[min(1120px,calc(100%-28px))]"><div className="flex items-center justify-between gap-4"><p className="font-mono text-[11px] tracking-[.08em] text-slate-500">02 / MODEL</p><a href="https://github.com/OTRI-run/otri/blob/main/METHODOLOGY.md" className="flex shrink-0 items-center gap-1 text-xs font-semibold text-blue-600 no-underline">Open methodology <ArrowUpRight size={14}/></a></div><div className="mt-6 grid min-w-0 gap-10 lg:grid-cols-[.82fr_1.18fr] lg:gap-20"><div className="min-w-0"><h2 className="text-[clamp(38px,5vw,62px)] font-bold leading-[.94] tracking-[-.06em]">Open method.<br/><span className="bg-gradient-to-r from-blue-700 to-cyan-500 bg-clip-text text-transparent">Traceable result.</span></h2><p className="mt-5 max-w-[440px] text-sm leading-7 text-slate-500">OTRI is being built so the scoring process can be understood, tested and reproduced. Official results and documented course data are validated before scoring.</p><div className="mt-6 flex flex-wrap items-center gap-2 font-mono text-[8px] text-slate-500"><GitBranch size={16} className="text-blue-600"/>same inputs + same scoring version <b className="text-blue-600">=</b> same result</div></div><div className="min-w-0 border-t border-slate-400/70">{pipeline.map(([n,title,desc])=><div key={n} className="grid min-w-0 grid-cols-[30px_minmax(0,1fr)_minmax(0,1.2fr)_18px] items-center gap-3 border-b border-slate-300 py-4"><b className="font-mono text-[9px] text-slate-600">{n}</b><strong className="text-[13px]">{title}</strong><span className="min-w-0 text-[11px] text-slate-500 max-sm:col-span-2 max-sm:col-start-2 max-sm:row-start-2">{desc}</span><ArrowUpRight size={14} className="text-blue-600"/></div>)}</div></div></div></section>
<section id="principles" className="bg-[#0b1220] py-14 text-white sm:py-20"><div className="mx-auto w-[min(1120px,calc(100%-28px))]"><div className="flex items-center justify-between"><p className="font-mono text-[11px] tracking-[.08em] text-slate-500">03 / PRINCIPLES</p><span className="font-mono text-[9px] tracking-[.08em] text-blue-400">NO BLACK BOX</span></div><h2 className="mt-5 text-[clamp(38px,5vw,62px)] font-bold leading-[.94] tracking-[-.06em]">Built in the open.</h2><div className="mt-9 grid border-t border-slate-700/80 sm:grid-cols-2 lg:grid-cols-5">{principles.map(([title,desc])=><article key={title} className="border-b border-slate-700/80 px-0 py-4 sm:border-r sm:px-4 lg:border-b-0"><small className="font-mono text-[9px] text-white">{title}</small><p className="mt-3 text-[11px] leading-5 text-slate-400">{desc}</p></article>)}</div></div></section>
<section className="bg-white py-14 sm:py-20"><div className="mx-auto grid w-[min(1120px,calc(100%-28px))] gap-8 lg:grid-cols-[1fr_.8fr] lg:gap-20"><div><p className="font-mono text-[11px] tracking-[.08em] text-slate-500">04 / ORGANIZERS</p><h2 className="mt-3 text-[clamp(38px,5vw,62px)] font-bold leading-[.94] tracking-[-.06em]">Start with<br/><span className="bg-gradient-to-r from-blue-700 to-cyan-500 bg-clip-text text-transparent">official results.</span></h2></div><div><p className="text-sm leading-7 text-slate-500">Race organizers provide official results and course details. OTRI validates the inputs and calculates the index.</p><a className={`mt-4 inline-flex items-center gap-1 text-xs font-semibold text-blue-600 no-underline ${FOCUS}`} href="prototype/organizer/">For organizers <ArrowUpRight size={14} aria-hidden="true"/></a></div></div></section>
<section id="about" className="border-y border-slate-200 bg-[linear-gradient(160deg,#eef4ff_0%,#f3f7fc_55%,#eaf1fb_100%)] py-14 sm:py-20"><div className="mx-auto grid w-[min(1120px,calc(100%-28px))] gap-8 lg:grid-cols-[1fr_.8fr] lg:gap-20"><div><p className="font-mono text-[11px] tracking-[.08em] text-slate-500">05 / ABOUT</p><h2 className="mt-3 text-[clamp(38px,5vw,62px)] font-bold leading-[.94] tracking-[-.06em]">Built by and<br/><span className="bg-gradient-to-r from-blue-700 to-cyan-500 bg-clip-text text-transparent">for the community.</span></h2></div><div><p className="text-sm leading-7 text-slate-500">OTRI started from a simple idea: local trail races and small organizers shouldn't need a closed, expensive ranking system just to give runners a fair way to compare performances. OTRI is free, open-source software built for runners and organizers alike — especially local races running on a small budget.</p><p className="mt-4 text-sm leading-7 text-slate-500">It's a community-driven project, and it's always looking for contributors and testers — developers, methodology reviewers, race organizers, and runners willing to try it against real races.</p><a className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-blue-600 no-underline" href="https://github.com/OTRI-run/otri/blob/main/CONTRIBUTING.md">Get involved <ArrowUpRight size={14}/></a></div></div></section>
<section className="bg-[linear-gradient(115deg,#1d4ed8_0%,#2563eb_48%,#0891b2_100%)] py-14 text-white sm:py-16"><div className="mx-auto flex w-[min(1120px,calc(100%-28px))] flex-col items-start"><p className="font-mono text-[11px] tracking-[.08em] text-blue-100">OPEN TRAIL RUNNING INDEX</p><h2 className="mt-2 text-[clamp(40px,5.8vw,70px)] font-bold leading-[.94] tracking-[-.065em]">Compare trail performances.<br/><span>Not just finish times.</span></h2><a className={`mt-7 inline-flex min-h-11 items-center gap-2 rounded-lg bg-white px-4 text-[13px] font-semibold text-blue-600 no-underline shadow-[0_10px_30px_rgba(0,0,0,.12)] ${FOCUS} focus-visible:outline-white`} href={EXAMPLE_HREF}>Try an example race <ArrowRight size={15} aria-hidden="true"/></a></div></section>
</main><footer className="border-t border-slate-200 bg-white py-6"><div className="mx-auto flex w-[min(1120px,calc(100%-28px))] flex-col items-start justify-between gap-3 sm:flex-row sm:items-center"><Logo/><nav className="flex flex-wrap items-center gap-x-5 gap-y-2 text-[12px] font-medium text-slate-500"><a href="https://github.com/OTRI-run/otri" className="inline-flex items-center gap-1.5 font-semibold text-[#0b1220] no-underline hover:text-blue-600"><GitHubMark size={15}/>GitHub</a><a href="prototype/#runners" className="no-underline hover:text-blue-600">Runners</a><a href="mailto:hello@otri.run" className="inline-flex items-center gap-1.5 no-underline hover:text-blue-600"><Mail size={14}/>hello@otri.run</a><a href="/privacy/" className="no-underline hover:text-blue-600">Privacy</a><a href="/terms/" className="no-underline hover:text-blue-600">Terms</a><a href="/data-policy/" className="no-underline hover:text-blue-600">Data policy</a></nav><span className="font-mono text-[8px] tracking-[.08em] text-slate-500">OPEN · TRANSPARENT · REPRODUCIBLE · INDEPENDENT</span></div></footer><BuildBanner/>
</div>}

createRoot(document.getElementById('root')).render(
  <ErrorBoundary home="./">
    <App />
  </ErrorBoundary>,
)
