import './main.css'
import React from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowUpRight, ChevronDown, Database, GitBranch, Mail, Mountain, ShieldCheck } from 'lucide-react'
import Logo from './components/Logo'
import BuildBanner from './components/BuildBanner'
import ErrorBoundary from './components/ErrorBoundary'
import { initMonitoring } from './lib/monitoring'
import './styles.css'

initMonitoring()

const principles=[['OPEN','Source code and methodology are public.'],['TRANSPARENT','Scores can be inspected and explained.'],['REPRODUCIBLE','Same inputs and version produce the same result.'],['TRACEABLE','Data provenance and permissions are recorded.'],['INDEPENDENT','OTRI develops its own methodology and infrastructure.']]
const pipeline=[['01','RESULTS','Official race data'],['02','VALIDATE','Quality checks'],['03','COURSE','Distance + elevation'],['04','MODEL','Versioned scoring'],['05','INDEX','Reproducible output']]


function App(){return <div id="top" className="src-main-app-div-1">
<header className="src-main-app-header-2"><div className="src-main-app-div-3"><Logo/><div className="src-main-app-div-4"><i className="src-main-app-i-5"/>IN DEVELOPMENT <span className="src-main-app-span-6">v0.x</span></div><nav className="src-main-app-nav-7"><a href="#why" className="src-main-app-a-8">Why</a><a href="#model" className="src-main-app-a-8">Model</a><a href="#principles" className="src-main-app-a-8">Principles</a><a href="#about" className="src-main-app-a-8">About</a><a className="src-main-app-a-8" href="prototype/#faq">FAQ</a><a className="src-main-app-a-9" href="https://github.com/OTRI-run/otri">GitHub <ArrowUpRight size={14}/></a></nav><a className="src-main-app-a-10" href="https://github.com/OTRI-run/otri">GitHub <ArrowUpRight size={13}/></a></div></header>
<div className="src-main-app-div-11"><div className="src-main-app-div-12"><i className="src-main-app-i-13"/>IN DEVELOPMENT <span className="src-main-app-span-6">v0.x</span></div></div>
<main>
<section className="src-main-app-section-14"><div className="src-main-app-div-15"><div className="src-main-app-div-16"><div className="src-main-app-div-17">OPEN TRAIL RUNNING INDEX <span className="src-main-app-span-18">·</span> OPEN BY DESIGN</div><h1 className="src-main-app-h1-19">A trail index<br/><em className="src-main-app-em-20">you can actually inspect.</em></h1><p className="src-main-app-p-21">Open the black box. Follow the data. Understand the score. OTRI is building a transparent, reproducible performance index from race results, course data and race context.</p><div className="src-main-app-div-22"><a className="src-main-app-a-23" href="#model">See how it works <ChevronDown size={15}/></a><a className="src-main-app-a-24" href="https://github.com/OTRI-run/otri">View source <ArrowUpRight size={15}/></a></div><div className="src-main-app-div-25"><span className="src-main-app-span-26">OPEN</span><span>TRANSPARENT</span><span>REPRODUCIBLE</span><span>INDEPENDENT</span></div></div>
<div className="src-main-app-div-27"><div className="src-main-app-div-28"><span>OTRI / INDEX ENGINE</span><span className="src-main-app-span-29"><i className="src-main-app-i-30"/>BUILDING</span></div><div className="src-main-app-div-31"><small className="src-main-app-small-32">WHY THIS SCORE?</small><strong className="src-main-app-strong-33">See what goes in.</strong><span className="src-main-app-span-34">See why it comes out.</span></div><div>{[[Database,'RESULTS','official data'],[Mountain,'COURSE','distance · elevation'],[ShieldCheck,'VALIDATION','quality + provenance']].map(([Icon,title,desc])=><div key={title} className="src-main-app-div-35"><Icon size={16} className="src-main-app-icon-36"/><span className="src-main-app-span-37">{title}</span><small className="src-main-app-small-38">{desc}</small></div>)}</div><div className="src-main-app-div-39"><b>OTRI INDEX</b><span className="src-main-app-span-40">VERSIONED · REPRODUCIBLE</span></div></div></div></section>
<section id="why" className="src-main-app-section-41"><div className="src-main-app-div-42"><div className="src-main-app-div-43"><div className="src-main-app-div-44">01</div><div className="src-main-app-div-16"><p className="src-main-app-p-45">WHY</p><h2 className="src-main-app-h2-46">Same distance.<br/><span className="src-main-app-span-47">Different challenge.</span></h2></div><p className="src-main-app-p-48">A 50 km race can be fast and runnable, or steep, technical and mountainous. Distance, elevation, terrain, course design, field strength, weather and altitude change what a finish time means.</p></div><div className="src-main-app-div-49"><div className="src-main-app-div-50"><small className="src-main-app-small-51">RACE A</small><b className="src-main-app-b-52">50 km</b><span className="src-main-app-span-53">+1,200 m · RUNNABLE</span></div><div className="src-main-app-div-54">≠</div><div className="src-main-app-div-55"><small className="src-main-app-small-51">RACE B</small><b className="src-main-app-b-52">50 km</b><span className="src-main-app-span-53">+3,400 m · TECHNICAL</span></div></div></div></section>
<section id="model" className="src-main-app-section-56"><div className="src-main-app-div-42"><div className="src-main-app-div-57"><p className="src-main-app-p-58">02 / MODEL</p><a href="https://github.com/OTRI-run/otri/blob/main/METHODOLOGY.md" className="src-main-app-a-59">Open methodology <ArrowUpRight size={14}/></a></div><div className="src-main-app-div-60"><div className="src-main-app-div-16"><h2 className="src-main-app-h2-46">Open method.<br/><span className="src-main-app-span-47">Traceable result.</span></h2><p className="src-main-app-p-61">OTRI is being built so the scoring process can be understood, tested and reproduced. Official results and documented course data are validated before scoring.</p><div className="src-main-app-div-62"><GitBranch size={16} className="src-main-app-span-26"/>same inputs + same scoring version <b className="src-main-app-span-26">=</b> same result</div></div><div className="src-main-app-div-63">{pipeline.map(([n,title,desc])=><div key={n} className="src-main-app-div-64"><b className="src-main-app-b-65">{n}</b><strong className="src-main-app-strong-66">{title}</strong><span className="src-main-app-span-67">{desc}</span><ArrowUpRight size={14} className="src-main-app-span-26"/></div>)}</div></div></div></section>
<section id="principles" className="src-main-app-section-68"><div className="src-main-app-div-42"><div className="src-main-app-div-69"><p className="src-main-app-p-58">03 / PRINCIPLES</p><span className="src-main-app-span-70">NO BLACK BOX</span></div><h2 className="src-main-app-h2-71">Built in the open.</h2><div className="src-main-app-div-72">{principles.map(([title,desc])=><article key={title} className="src-main-app-article-73"><small className="src-main-app-small-74">{title}</small><p className="src-main-app-p-75">{desc}</p></article>)}</div></div></section>
<section className="src-main-app-section-41"><div className="src-main-app-div-76"><div><p className="src-main-app-p-58">04 / ORGANIZERS</p><h2 className="src-main-app-h2-77">Start with<br/><span className="src-main-app-span-47">official results.</span></h2></div><div><p className="src-main-app-p-78">Race organizers provide official results and course details. OTRI validates the inputs and calculates the index.</p><a className="src-main-app-a-79" href="https://github.com/OTRI-run/otri/blob/main/docs/organizer-upload.md">Organizer documentation <ArrowUpRight size={14}/></a></div></div></section>
<section id="about" className="src-main-app-section-80"><div className="src-main-app-div-76"><div><p className="src-main-app-p-58">05 / ABOUT</p><h2 className="src-main-app-h2-77">Built by and<br/><span className="src-main-app-span-47">for the community.</span></h2></div><div><p className="src-main-app-p-78">OTRI started from a simple idea: local trail races and small organizers shouldn't need a closed, expensive ranking system just to give runners a fair way to compare performances. OTRI is free, open-source software built for runners and organizers alike — especially local races running on a small budget.</p><p className="src-main-app-p-81">It's a community-driven project, and it's always looking for contributors and testers — developers, methodology reviewers, race organizers, and runners willing to try it against real races.</p><a className="src-main-app-a-79" href="https://github.com/OTRI-run/otri/blob/main/CONTRIBUTING.md">Get involved <ArrowUpRight size={14}/></a></div></div></section>
<section className="src-main-app-section-82"><div className="src-main-app-div-83"><p className="src-main-app-p-84">OPEN TRAIL RUNNING INDEX</p><h2 className="src-main-app-h2-85">Compare trail performances.<br/><span>Not just finish times.</span></h2><a className="src-main-app-a-86" href="https://github.com/OTRI-run/otri">Explore OTRI <ArrowUpRight size={15}/></a></div></section>
</main><footer className="src-main-app-footer-87"><div className="src-main-app-div-88"><Logo/><a href="mailto:hello@otri.run" className="src-main-app-a-89"><Mail size={14}/>hello@otri.run</a><span className="src-main-app-span-90">OPEN · TRANSPARENT · REPRODUCIBLE · INDEPENDENT</span></div></footer><BuildBanner/>
</div>}

createRoot(document.getElementById('root')).render(
  <ErrorBoundary home="./">
    <App />
  </ErrorBoundary>,
)
