import { useState } from 'react'
import { ArrowDown, ArrowUpRight, Check, Copy } from 'lucide-react'
import { Wordmark } from '../src/components/Logo'
import './Media.css'

const ASSETS = new URL('../brand/uphill/', window.location.href.split('#')[0]).href
const ABOUT = 'OTRI — the Open Trail Running Index — turns a course and finish time into a comparable trail-running score. Its scoring methodology and code are public and versioned. Free for runners and race organizers, OTRI measures performance; it does not certify races. otri.run'
const versions = [
  { id: 'color', name: 'Primary', tone: 'brand', ground: 'paper', note: 'Ink lettering. Electric blue summit and arrow. The default on light backgrounds.' },
  { id: 'black', name: 'Black', tone: 'black', ground: 'paper', note: 'One neutral ink for printing, race bibs and documents.' },
  { id: 'white', name: 'White', tone: 'white', ground: 'electric', note: 'A single white silhouette on solid color or dark photography.' },
  { id: 'on-dark', name: 'On dark', tone: 'on-dark', ground: 'ink', note: 'White lettering with the electric blue details retained.' },
]
export default function Media() {
  const [selected, setSelected] = useState('color')
  const [copied, setCopied] = useState('')
  const [error, setError] = useState('')
  const current = versions.find(v => v.id === selected)
  async function copy(key, value) {
    try { await navigator.clipboard.writeText(value); setCopied(key); setError('') }
    catch { setCopied(''); setError('Copy is unavailable. Select and copy the text below.') }
  }
  return <main className="brand-page">
    <header className="brand-intro">
      <div><p className="brand-kicker">OTRI / MEDIA & BRAND</p><h1>One clear identity.<br /><span>On every trail.</span></h1></div>
      <div className="brand-intro-side"><p>Our name, our colors, our mark.<br />Everything you need to present OTRI clearly.</p><a className="brand-button" href={`${ASSETS}otri-uphill-kit.zip`} download>Download the brand kit <ArrowDown size={16} /></a><small>8 outlined SVGs, 3 avatars + usage notes · ZIP</small></div>
    </header>
    <section className="brand-lab" aria-label="Interactive logo preview">
      <div className="brand-lab-bar"><span>01 / THE WORDMARK</span><div role="group" aria-label="Logo version">{versions.map(v => <button key={v.id} aria-pressed={selected === v.id} onClick={() => setSelected(v.id)}>{v.name}</button>)}</div></div>
      <div className={`brand-stage ground-${current.ground}`}><span className="brand-stage-label">UPHILL / BLACK ELECTRIC</span><Wordmark tone={current.tone} size={180} /><span className="brand-stage-caption">Open Trail Running Index</span></div>
      <div className="brand-lab-foot"><p>{current.note}</p><a href={`${ASSETS}otri-uphill-${selected}.svg`} download>Download {current.name.toLowerCase()} SVG <ArrowDown size={15} /></a></div>
    </section>
    <section className="brand-story"><div><p className="brand-kicker">THE IDEA</p><h2>A summit. A direction.<br />A name you can read.</h2></div><div className="brand-story-grid"><article><b>01</b><h3>Read the name</h3><p>Strong lowercase lettering keeps OTRI recognizable, even in a compact website header.</p></article><article><b>02</b><h3>Find the summit</h3><p>The mountain takes the place of the dot above the i. A small detail with a clear connection to the trail.</p></article><article><b>03</b><h3>Keep moving</h3><p>The rising arrow gives the mark direction. The blue details stay crisp against the dark lettering.</p></article></div></section>
    <section className="brand-section"><div className="brand-section-head"><div><p className="brand-kicker">02 / LOGO LIBRARY</p><h2>The right file for your background.</h2></div><p>Scalable vectors, with every letter outlined.<br />No fonts or external files required.</p></div><div className="brand-downloads">{versions.map(v => <article key={v.id}><div className={`brand-tile ground-${v.ground}`}><Wordmark tone={v.tone} size={76} /></div><div className="brand-download-info"><div><h3>{v.name}</h3><p>{v.note}</p></div><a href={`${ASSETS}otri-uphill-${v.id}.svg`} download aria-label={`Download ${v.name} SVG`}><ArrowDown size={19} /><span>SVG</span></a></div></article>)}</div></section>
    <section className="brand-section" id="domain-logos"><div className="brand-section-head"><div><p className="brand-kicker">THE DOMAIN LOCKUP</p><h2>Take otri.run with you.</h2></div><p>The name and the address together.<br />For race banners, social posts and partner websites.</p></div><div className="brand-downloads">{versions.map(v => <article key={v.id}><div className={`brand-tile ground-${v.ground}`}><img src={`${ASSETS}otri-run-${v.id}.svg`} alt={`otri.run — ${v.name}`} style={{ width: '100%', maxWidth: 340, height: 'auto', maxHeight: 100 }} /></div><div className="brand-download-info"><div><h3>otri.run / {v.name}</h3><p>{v.note}</p></div><a href={`${ASSETS}otri-run-${v.id}.svg`} download aria-label={`Download otri.run ${v.name} SVG`}><ArrowDown size={19} /><span>SVG</span></a></div></article>)}</div></section>
    <section className="brand-section" id="avatars"><div className="brand-section-head"><div><p className="brand-kicker">PROFILE PICTURES</p><h2>The mark, cut to a circle.</h2></div><p>Square, 1024 px, drawn so the mark stays clear of the crop.<br />The same monogram is the site's icon.</p></div><div className="brand-downloads">{[['otri-avatar-1024.png', 'Monogram on ink', 'For profiles on any platform. The default.', 'ink'], ['otri-avatar-light-1024.png', 'Monogram on white', 'Where the profile sits on a dark page.', 'paper'], ['otri-avatar-wordmark-1024.png', 'Wordmark on ink', 'Where the name should read in the circle.', 'ink']].map(([file, name, note, ground]) => <article key={file}><div className={`brand-tile ground-${ground}`}><img src={`${ASSETS}${file}`} alt={`OTRI avatar: ${name}`} style={{ width: 120, height: 120, borderRadius: '50%' }} /></div><div className="brand-download-info"><div><h3>{name}</h3><p>{note}</p></div><a href={`${ASSETS}${file}`} download aria-label={`Download ${name}`}><ArrowDown size={19} /><span>PNG</span></a></div></article>)}</div></section>
    <section className="brand-section"><div className="brand-section-head"><div><p className="brand-kicker">03 / COLOR</p><h2>Ink. Electric. White.</h2></div><p>Keep the palette simple.<br />Blue is the accent; ink carries the name.</p></div><div className="brand-colors">{[['Ink','#17202C','The wordmark and primary text.'],['Electric','#3576F6','The summit, arrow and brand accents.'],['White','#FFFFFF','Clear space and reversed lettering.']].map(([name,hex,note]) => <button key={hex} onClick={() => copy(hex,hex)} style={{ background: hex, color: name === 'White' ? '#17202c' : '#ffffff' }} aria-label={`Copy ${name} color ${hex}`}><span>{name}{copied === hex ? <Check size={18} /> : <Copy size={16} />}</span><strong>{hex}</strong><small>{note}</small></button>)}</div><p role="status" className="brand-copy-status">{error || (copied ? `Copied ${copied === 'about' ? 'description' : copied}.` : 'Select a color to copy its hex value.')}</p></section>
    <section className="brand-rules"><div><p className="brand-kicker">04 / IN USE</p><h2>Give the mark<br />room to breathe.</h2><p>Keep the artwork intact. Leave at least one i-stem width of clear space around it. Use a width of 80 px or more for the full wordmark.</p></div><div className="brand-clearspace"><div><Wordmark size={105} /></div><span>Clear space on every side</span></div><ul><li><Check size={17} /> Use the supplied proportions and colors.</li><li><Check size={17} /> Choose a version with clear background contrast.</li><li><Check size={17} /> Keep the summit, lettering and arrow together.</li><li><span aria-hidden="true">×</span> Avoid stretching, shadows, gradients or extra outlines.</li></ul></section>
    <section className="brand-section brand-press"><div><p className="brand-kicker">05 / WORDS FOR THE PRESS</p><h2>Open Trail Running Index.</h2><p>Write the name as OTRI. Describe a race as “scored with OTRI”, never “OTRI certified”.</p><a href="mailto:hello@otri.run">Press & brand enquiries <ArrowUpRight size={16} /></a></div><div className="brand-quote"><div><span>ABOUT OTRI</span><button onClick={() => copy('about', ABOUT)}>{copied === 'about' ? <Check size={15} /> : <Copy size={15} />}{copied === 'about' ? 'Copied' : 'Copy text'}</button></div><p>{ABOUT}</p></div></section>
    <footer className="brand-end"><span>Use these assets to identify OTRI accurately. Do not imply endorsement or certification.</span><a href={`${ASSETS}otri-uphill-kit.zip`} download>Get the complete kit <ArrowDown size={15} /></a></footer>
  </main>
}
